// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqrvjfgcbhpmsqitvune.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxcnZqZmdjYmhwbXNxaXR2dW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzEwMTEsImV4cCI6MjA2NjM0NzAxMX0.BSkMPz_Om6dzLy5Aya0B0HkcbWWvPUnXnY6GyzJ6lyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});